services:
  ffhb-championship-calendar-generator_container:
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ../:/app_ffhb-championship-calendar-generator:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5000:5000
      - 3000:3000
    networks:
      - ffhb-championship-calendar-generator_network

networks:
  ffhb-championship-calendar-generator_network:
    driver: 'bridge'
