version: '3'
services:
  ffhbchampionshipcalendar_container:
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ../:/app_ffhbchampionshipcalendar:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5000:5000
      - 3000:3000
    networks:
      - ffhbchampionshipcalendar_network

networks:
  ffhbchampionshipcalendar_network:
    driver: 'bridge'
